// This file was auto-generated by prisma-generator-typescript-interfaces

export type planType = "premium" | "free" | "enterprise";

export type Priority = "LOW" | "MEDIUM" | "HIGH";

export interface User {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
  sessions?: Session[];
  accounts?: Account[];
  todos?: Todo[];
  categories?: Category[];
  plans?: plan[];
}

export interface Session {
  id: string;
  expiresAt: Date;
  token: string;
  createdAt: Date;
  updatedAt: Date;
  ipAddress: string | null;
  userAgent: string | null;
  userId: string;
  user?: User;
}

export interface plan {
  id: string;
  planType: planType;
  userId: string;
  user?: User;
}

export interface Account {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  user?: User;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: string | null;
  password: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface Todo {
  id: string;
  content: string;
  completed: boolean;
  createdAt: Date;
  updatedAt: Date;
  userId: string;
  user?: User;
  categoryId: string | null;
  category?: Category | null;
  priority: Priority;
}

export interface Category {
  id: string;
  name: string;
  userId: string;
  user?: User;
  todos?: Todo[];
  createdAt: Date;
  updatedAt: Date;
}
